config/routes.rb
Penncoursefinder::Application.routes.draw do
  
  resources :courses, :only => [:index, :show]
  resources :queries, :only => [:index, :new, :show, :create]
  resources :querynumbers, :only => [:index, :new, :show, :create]
  resources :querytimings, :only => [:index, :new, :show, :create]
  
  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <hr style="solid:#000;" />
  <div id="footer"><font face="palatino">
    <div id="footer-inner" class="container_12">
      <%= link_to "Home", root_path %>
      <span>|</span> <%= link_to "All Courses", courses_path %>
      <p id="copyright">
          Copyright &copy; 2012
          <a><strong>Penn Course Finder</strong></a>
      </p>
      </font>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<br><br>

<font face="palatino", font size="4">

<div class="logobox"> 
<div class="left";>
  <%= link_to image_tag("PSA_LOGO_final.png",{:alt => "Penn Course Finder"}), root_path %>
</div>
</div>

  <div class="headerboxsignin">
    <ul class="nav-bar">
        <li>
		<%= link_to "Home", root_path %>
        </li>
        <li>
		<%= link_to "All Courses", courses_path %>
        </li>
        <li>
		<%= link_to "Requirements", queries_path %>
        </li>
	<li>
		<%= link_to "Course Levels", querynumbers_path %>
        </li>
	<li>
		<%= link_to "Section Finder", querytimings_path %>
        </li>
  </div>

    </ul>
  
</font>

<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Penn Course Finder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="orbit-wrapper">
  <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash_<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <br><br>
  </div>
</div>
</body>
</html>